### ISSUE TITLE
整備作業更新跳出錯誤

### ISSUE THREAD

**Issue by iting-chang** [aglean/issue_tracker#234]
## 目前的情況 Current Behavior

當使用者進入整備作業，選擇其中一筆整備資料進行編輯時，無論編輯哪個欄位，按下「執行」按鈕都會跳出「作業階段錯誤」的彈跳視窗，但是實際上資料是有更新成功的。
## 重現問題的步驟 Steps to Reproduce

1.進入整備作業
2.選擇其中一筆整備資料
3.進入編輯畫面
4.掃描輸入標籤資料
5.按下「執行」儲存資料

## 對應的環境 Context (Environment)

- 作業系統
  - windows 10

**Comment by chiutung-chen** [comment]
fixed
