### ISSUE TITLE
每一筆產品、文章、遊程、講堂、活動的推薦區無法正常顯示

### ISSUE THREAD

**Issue by iting-chang** [aglean/issue_tracker#236]
## 目前的情況 Current Behavior

後台已指定了推薦區應顯示的產品、文章、遊程、講堂或活動，但在前台無法正常顯示，如下圖。

### 潮好物推薦區
![screenshot-phbay aglean com-2021 12 14-10_19_17](https://user-images.githubusercontent.com/30255320/145921478-6885e11b-4173-4c2a-bc99-f9ebf0dff494.png)

### 潮人物推薦區
(沒有出現推薦區)
![screenshot-phbay aglean com-2021 12 14-10_24_43](https://user-images.githubusercontent.com/30255320/145921810-523a4415-ed20-4fd6-8962-60f56dea98de.png)

### 潮好玩推薦區
![screenshot-phbay aglean com-2021 12 14-10_29_15](https://user-images.githubusercontent.com/30255320/145922979-3dbabaea-13a0-476d-a8a1-66ba7fd30bea.png)

### 潮活動推薦區
![screenshot-phbay aglean com-2021 12 14-10_31_44](https://user-images.githubusercontent.com/30255320/145922502-4359b36e-a1d2-44bb-9700-1957406dba93.png)

### 潮講堂推薦區
推薦區沒有出現
![screenshot-phbay aglean com-2021 12 14-10_34_52](https://user-images.githubusercontent.com/30255320/145922810-553eae39-d2dd-4e2f-9e04-0eb52d72dfa9.png)

## 對應的環境 Context (Environment)

- 作業系統
  - macOS
- 瀏覽器
  - chrom

**Comment by chiutung-chen** [comment]
fixed
