### ISSUE TITLE
新增出貨作業開始掃碼時，掃碼計數問題

### ISSUE THREAD

**Issue by iting-chang** [aglean/issue_tracker#256]
## 目前的情況 Current Behavior

新增出貨作業開始掃碼時，偶爾發生掃入ENTER的狀況，且上方紀錄標籤數量的計數也會把ENTER算進數量裡，但在儲存後，重新點進該筆記錄，又會正常顯示數量。

## 正確的情況 Expected Behavior

只有ENTER不應計入標籤數量
## 對應的環境 Context (Environment)

- 作業系統
  - windows 7

**Comment by chiutung-chen** [comment]
If we can not figure out the right solution. We should close this issue with invalid status.
