### ISSUE TITLE
專案未於時間內分群完畢而導致直接結案

### ISSUE THREAD

**Issue by iting-chang** [aglean/issue_tracker#257]
專案設定：
寄送一次自動結案
寄送對象約22萬筆
預計寄送時間每月8號上午8點

專案排程：
8:01開始分群
8:21開始寄送已分群完成的email名單
**異常狀況：8:21尚未完成分群，無法寄送**
8:40執行寄送完成檢查，寄送筆數為0直接結案
**異常狀況：並未寄出任何一封信卻可以結案，畫面也無顯示異常狀況資訊，不合常理。**

後續處理：
先請客戶檢查server是否資源不足，導致分群速度異常。
未來程式優化待討論。

**Comment by chiutung-chen** [comment]
Should this issue been investigated? Should be closed, if it's completed.

**Comment by tzuchaolin** [comment]
我在等3/8的專案寄送結果，沒有問題的話就可以close。

**Comment by tzuchaolin** [comment]
專案已寄送完畢，機器I/O也正常。
![截圖 2022-03-08 下午4 19 15](https://user-images.githubusercontent.com/60908194/157195596-3bd46a19-bd8d-4880-978a-4436356d2ab0.png)
![截圖 2022-03-08 下午4 19 42](https://user-images.githubusercontent.com/60908194/157195664-3b85dd17-fd0c-47b3-8df2-15e1fcfb90aa.png)
![截圖 2022-03-08 下午4 20 10](https://user-images.githubusercontent.com/60908194/157195753-7ec423fc-5529-44ef-a7c7-fc54d4eb4396.png)
