### ISSUE TITLE
列印出來的提領單希望可以顯示「代理備註」(等待報價)

### ISSUE THREAD

**Issue by iting-chang** [aglean/issue_tracker#263]
## 目前的情況 Current Behavior

將代理備註擺放在托運備註下方
如下圖：
![5_ClaimsPrint1](https://user-images.githubusercontent.com/30255320/150270304-2eb5166e-fa85-437e-85f2-d6f2e808f4f1.png)

- 作業系統
  - windows 10

**Comment by chiutung-chen** [comment]
This issue had been posted for more than 3 month, please close it with "invalid" status.
