### ISSUE TITLE
賈維斯商標後台訂單編號排序有誤

### ISSUE THREAD

**Issue by Yihsunkaka** [aglean/issue_tracker#275]
* 客戶於2022.03.15 AM09:51 Line回報
1. 後台申請案訂單編號排序有誤
![申請p1](https://user-images.githubusercontent.com/53588635/158294348-57d4f395-ee83-4fa6-b3cc-d97d2726aca7.png)
2. 後台帳務管理訂單編號排序有誤(202203140005應該第1頁第1筆，卻顯示在第2頁第1筆)
![帳務p1](https://user-images.githubusercontent.com/53588635/158294458-60bf30d0-765c-49e4-98a1-20f3ab54707d.png)
![帳務p2](https://user-images.githubusercontent.com/53588635/158294464-ffbd48fd-66f2-4c13-90bb-7cb0ab6f25dd.png)

=======================================================================================
* 前台全部頁面footer位置拉大時會跑版(客戶未發現，請一併處理)
![截圖 2022-03-15 10 36 43](https://user-images.githubusercontent.com/53588635/158294886-9cf38c8a-0f8c-4462-a830-f8fc94f5130e.png)

**Comment by tzuchaolin** [comment]
fixed

**Comment by Yihsunkaka** [comment]
3/15(二)下午13:45回覆客戶修好，客戶即時確認回覆正常ok
