### ISSUE TITLE
UI調整

### ISSUE THREAD

**Issue by iting-chang** [aglean/issue_tracker#278]
1.每日簽到頁面加按鈕2頁

![調整1-1](https://user-images.githubusercontent.com/30255320/162355056-d47170bb-5607-4daf-8f62-51cda7a14f28.png)

![調整1-2](https://user-images.githubusercontent.com/30255320/162355068-59559caa-0424-4044-9164-14a204266e1f.png)

2. 限時任務一覽表表頭文字調整

![調整2](https://user-images.githubusercontent.com/30255320/162355151-9d117039-d2f8-41e7-8ceb-05d55c7112bb.png)

**Comment by tzuchaolin** [comment]
pushed to branch qz.
