### ISSUE TITLE
移除提領單批次列印後自動重load畫面的功能

### ISSUE THREAD

**Issue by iting-chang** [aglean/issue_tracker#280]
**為了什麼事情，想加入這個新功能**
原本客戶希望可以在批次列印提領單完畢後自動重Load畫面，但是重新Loading畫面後，原本的篩選條件就會消失，反而需要重下條件搜尋，因此希望可以恢復原本的做法。

**說明新功能的內容**
原本的做法是，列印完畢後，跳出彈跳視窗提示「列印完成」，按下確認後停留原畫面，提領單狀態也是維持在「未列印」狀態，切換頁面後，狀態才會更新。

**有其他的處理方式嗎？**
無

**額外資訊**
無

**Comment by chiutung-chen** [comment]
Sorry, I can not pass search parameters to the backend. I will revert to NOT reload status.
