### ISSUE TITLE
系統通知信，信件內容調整

### ISSUE THREAD

**Issue by iting-chang** [aglean/issue_tracker#284]
**描述錯誤問題**
系統通知信下方固定出現的資料待調整。

**如何重現問題**
請依紅字標記處調整內容
![截圖 2022-05-04 18 15 26](https://user-images.githubusercontent.com/30255320/166664543-a61a4974-863e-4851-8221-b592e62d71af.png)

**Comment by tzuchaolin** [comment]
done.
