### ISSUE TITLE
系統收據內容更新

### ISSUE THREAD

**Issue by iting-chang** [aglean/issue_tracker#285]
**描述錯誤問題**
系統收據固定出現的資料待調整。

**如何重現問題**
請依紅字標記處調整內容
![截圖 2022-05-04 20 09 55](https://user-images.githubusercontent.com/30255320/166679332-99146cb9-3fe5-4ad1-974a-fb7bb3c8aa40.png)

**Comment by tzuchaolin** [comment]
done.
