### ISSUE TITLE
忘記密碼不會寄發重設密碼信

### ISSUE THREAD

**Issue by Yihsunkaka** [aglean/issue_tracker#286]
客戶於2022/05/05 16:22 Line通報bug
使用者忘記密碼，填入email送出後，卻未能收到密碼重設信件
客戶自行操作也亦同
我司於測試機測試能收到信件，並請工程師查明原因

**Comment by tzuchaolin** [comment]
因為該使用者當初使用google第三方登入，has_usable_password() = False
https://stackoverflow.com/questions/20325729/django-reset-password-not-sending-email
