### ISSUE TITLE
編輯出貨時，使用標籤移除功能再加入一枚新標籤時，畫面右邊區塊的標籤數量異常

### ISSUE THREAD

**Issue by iting-chang** [aglean/issue_tracker#287]
**描述錯誤問題**
編輯出貨時，使用標籤移除功能再加入一枚新標籤時，畫面右邊區塊的標籤數量異常

**如何重現問題**
重現問題的步驟：
1. 進入出貨作業
2. 點選一張待出貨的出貨作業
3. 進入編輯出貨畫面
4. 使用左下角的移除標籤功能，移除一個產品
5. 使用左下角的新增標籤功能，新增一個產品
6. 訂購品項列表數量正確，但是在畫面右邊的標籤數量多一，且剛剛移除的標籤號碼還存在

**系統環境 (請加入以下資訊)：**
 - OS: win10

**Comment by chiutung-chen** [comment]
Couldn't reproduce the error. Remove scan result trim function as preventive action.
